name: Shaun Wu
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3873675772920251
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#8c643a'
    - '#29b34b'
    - '#a2a2a2'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
